### ISSUE TITLE
Wherefore art thou, SoftSetHook?

### ISSUE THREAD

**Issue by colingourlay** [nolanlawson/vdom-serialized-patch#2]
Hey @nolanlawson, any reason you left SoftSetHooks out when it seems like `vdom-as-json` supports them? Without them, we can't set/patch correct `<input/>` values as they're left as plain objects, and end up getting rendered as `[object "Object"]`.

**Comment by nolanlawson** [comment]
Yeah, I think this is just one thing I forgot to implement. I didn't need it for my own use case. Happy to accept a PR, though! :)

**Comment by JakeChampion** [comment]
I think this can be closed :-)

**Comment by nolanlawson** [comment]
yup, fixed by #3
