### ISSUE TITLE
Handling events

### ISSUE THREAD

**Issue by matthewp** [nolanlawson/vdom-serialized-patch#6]
I would like to possibly add event handling to the serialized object. The patch would have to be able to contain events that need to be added / removed, but it would be up to user code to do the handling.

I'll have to familiarize myself with the format, but what I think is needed is something like: `"addedEvents": ["click", "blur"], "removedEvents": ["mouseup"] `

Then it could possibly be used something like this (is this a good api?):

```js
function handleEvent(ev) {
  worker.postMessage({
    type: ev.type,
    msg: "something happened..."
  });
}

applyPatch(el, serializedPatch, {
  handleEvent: handleEvent
});
```

Whether the API is good or not, how feasible is this?

**Comment by nolanlawson** [comment]
How would the functionality itself be handled? Correct me if I'm wrong, but wouldn't you need to serialize the listener functions as well? Otherwise it seems reasonable to me. :)

**Comment by matthewp** [comment]
It depends on what you are trying to do. In my case I just want to know what type of event happened, send that back to the worker and handle it somewhat globally. I have enough information in the event, I don't need to call the real handler (which is on the worker side).

If you wanted to call the listener function I would imagine it might work like this (not knowing vdom's structure super-well). You would want to know the path to the VNode within the associated tree. Maybe `handleEvent` would get that info as a second argument:

**window.js**
```js
function handleEvent(ev, path) {
  let cloned = Object.assign({
    path: path
  }, ev);
  worker.postMessage(cloned);
}

applyPatch(el, serializedPatch, {
  handleEvent: handleEvent
});
```

**worker.js**

```js
let tree; // this is my cached VNode tree

onmessage = function(msg){
  let ev = msg.data;
  let propName = `ev-${ev.type}`;

  // Find the VNode within the tree
  let vnode = find(tree, ev.path)

  // Call the function
  vnode[propName](ev);  
};
```

This is pseudocode since I don't know the VNode structure all that well, been a while.  This assumes events are set up using the `ev-click` convention.

**Comment by nolanlawson** [comment]
On second thought I wonder if it wouldn't make more sense for you to implement this as a fork of this project. Looking back on the code I believe I started from the assumption that the patch would be extremely simple in order to optimize the patch size as much as possible. I might be hesitant to merge the PR if the resulting changes will balloon the code size.

OTOH I would encourage you to work on this since worst case scenario is that I would kindly ask you to make a forked project. :D

**Comment by matthewp** [comment]
No problem 👍
