### ISSUE TITLE
Tests are failing

### ISSUE THREAD

**Issue by rksm** [nolanlawson/vdom-serialized-patch#7]
Thanks for the project, very useful!

I wanted to submit a bug report for a specific issue but when trying to write a test I found out that after a `git clone` and `npm install` the tests are already failing.

Are there any other setup steps? A broken dependency?

`node -v` => v7.5.0
`npm -v` => 4.1.2

**Comment by nolanlawson** [comment]
What are the test failures and what's your OS? The tests are passing in Travis: https://travis-ci.org/nolanlawson/vdom-serialized-patch

**Comment by rksm** [comment]
It really seems to be a dependency issue. I forked your repo and forced a travis run without changing anything: https://travis-ci.org/LivelyKernel/vdom-serialized-patch

It looks like that `____UnDeFiNeD____` properties aren't removed. This actually is the issue I wanted to report in the first place.

**Comment by nolanlawson** [comment]
You're right; I can reproduce locally. Apparently a patch/minor release in a dependency broke this project. I'll investigate and downgrade as necessary.

**Comment by nolanlawson** [comment]
Fixed in 1.0.8. There was a breakage in vdom-as-json due to https://github.com/nolanlawson/vdom-as-json/pull/4

**Comment by nolanlawson** [comment]
I've now enabled GreenKeeper which of course will fail until I fix the vdom-as-json breakage, but for the time being I'll probably just keep it downgraded because I don't have the time for this project: https://github.com/nolanlawson/vdom-serialized-patch/pull/8

**Comment by rksm** [comment]
Thank you very much!
